[package]
name = "rustdoku-cli"
version = "0.1.0"
description = "Solves and generates sudokus"
authors = ["Ville Orkas <ville@orkas.fi>"]
edition = "2018"

[dependencies]
clap = "*"
rayon = "*"
rustdoku-sudoku = { path = "../sudoku" }