[package]
name = "rustdoku-sudoku"
version = "0.1.0"
description = "Solves and generates sudokus"
authors = ["Ville Orkas <ville@orkas.fi>"]
edition = "2021"

[dependencies]
itertools = "*"
thiserror = "*"
rand = "*"
ahash = "*"
once_cell = "*"
rayon = "*"
